### ISSUE TITLE
Cannot get value when value is set to `value`

### ISSUE THREAD

**Issue by leo-galleguillos** [laminas/laminas-cache-storage-adapter-memcached#5] opened 2020-11-10 20:40 UTC
### Bug Report

We noticed recently that setting a memcached value of string `value` returns NULL instead of the expected string `value`.

|    Q        |   A
|------------ | ------
| Version(s)  | 1.0.1

#### Summary

One of our unit tests started failing. We eventually realized that it was because we were testing with a memcached value of string `value`. Once we updated our unit tests to test with any other string, such as `val` or `12345`, the unit tests started working again.

#### Current behavior

When setting a memcached value to `value` and then trying to get this value later, this returned value is `NULL` instead of `value`.

#### How to reproduce

```
use Laminas\Cache\Storage\Adapter\Memcached as LaminasMemcached;
use Laminas\Cache\Storage\Adapter\MemcachedOptions as LaminasMemcachedOptions;
use Laminas\Cache\Storage\Adapter\MemcachedResourceManager as LaminasMemcachedResourceManager;

$laminasMemcachedResourceManager = new LaminasMemcachedResourceManager();
$laminasMemcachedResourceManager->addServer('default', 'localhost');

$laminasMemcachedOptions = new LaminasMemcachedOptions();
$laminasMemcachedOptions->setResourceManager($laminasMemcachedResourceManager);

$laminasMemcached = new LaminasMemcached($laminasMemcachedOptions);

$laminasMemcached->setItem('foo', 'value');
var_dump($laminasMemcached->getItem('foo'));
```

The above code dumps `NULL`.

Interestingly, if the value is set to something other than `value`, then the code executes as expected.
#### Expected behavior

The above code should dump `string(5) "value"`

**Comment by boesing** [comment] 2020-11-17 22:57
Thanks for reporting this issue, @leo-galleguillos!
I'll have a look on this later this week as I am planning to do some releases anyway.

**Comment by boesing** [comment] 2021-04-08 23:20
Wow, this totally went under the radar... github definitely needs a screen with a list of open, self-assigned issues.

----

I've tried to reproduce this issue with the following setup.

| Software | Version 
| ---- | ---- |
| PHP | 5.6
| ext-memcached | 2.2.0
| memcached | 1.6.9

I've used the code mentioned in the issue description as follows within a unit test:

```php
$resourceManager = new \Laminas\Cache\Storage\Adapter\MemcachedResourceManager();
$resourceManager->addServer('default', 'localhost');

$options = new \Laminas\Cache\Storage\Adapter\MemcachedOptions();
$options->setResourceManager($resourceManager);

$cache = new \Laminas\Cache\Storage\Adapter\Memcached($options);
$cache->setItem('foo', 'value');
$this->assertSame('value', $cache->getItem('foo'));
```

The test is passing. I've also tested with PHP 7.0, 7.1, 7.2, 7.3 and 7.4 and cannot reproduce this (ext-memcached was 3.1.5 for these).

Do you probably have some `plugin` which is manipulating the value like serializers?

**Comment by boesing** [comment] 2021-08-01 02:21
Closing here as we could not reproduce the bug.

**Closed as completed by boesing** 2021-08-01 02:21 UTC
Labels: Invalid
